---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pipelines
- name: terraform-state
- name: config 
# for config/FOUNDATION/pipeline-vars/prepare-credhub-secrets-from-terraform-state.sh


# all params are required to be filled out
params:

  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  # - Required
  # - Credentials to talk to credhub server

  CREDHUB_CA_CERT:
  # - Optional
  # - This is only necessary if your Concourse worker
  #   is not already configured to trust the CA used for Credhub.
  # - If more than one CA cert is required (ie the UAA),
  #   the CA certs can be concatenated together and separated by a newline.
  #   For example,
  #   CREDHUB_CA_CERT: |
  #     -----BEGIN CERTIFICATE-----
  #     ...credhub cert...
  #     -----END CERTIFICATE-----
  #     -----BEGIN CERTIFICATE-----
  #     ...UAA cert...
  #     -----END CERTIFICATE-----

  TERRAFORM_STATE_FILE_PATH: terraform.tfstate

  SHELL_FILE: pipeline-vars/set-credhub-from-terraform-state.sh
  # - Optional
  # shell path to run.

  PREFIX: /concourse/main

  PIPELINE_NAME: ""
  # naming rule is "$PREFIX/${PIPELINE_NAME}/key...""
  
run:
  path: pipelines/tasks/prepare-credhub-secrets-from-terraform-state.sh
