version: '3'

services:

  uaa:
    image: pcfseceng/uaa
    volumes: ["./uaa.yml:/uaa/uaa.yml"]
    ports: ["8080:8080"]  ## donot change this port
    restart: always

  credhub:
    #image: ampersand8/credhub ##  credhub login ok but, when set value error
    image: orangeopensource/credhub
    #image: springcloudservices/credhub-server
    ports: ["9000:9000"]
    links:
    - uaa
    depends_on:
    - uaa
    environment:
      #UAA_URL: http://localhost:8080/uaa  ## error-> failed to interpolate task config: var lookup 'hello': invalid character '<' looking for beginning of value
      #UAA_URL: http://192.168.67.1:8080/uaa  ## <-- set this to HOST machine IP. $ ifconfig | grep inet
      UAA_URL: http://192.168.50.1:8080/uaa  ## <-- set this to HOST machine IP. $ ifconfig | grep inet
      UAA_INTERNAL_URL: http://uaa:8080/uaa

  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    #image: concourse/concourse:4.2.1
    #image: concourse/concourse
    image: concourse/concourse:6.0.0
    command: quickstart
    privileged: true
    #volumes: ["./server_ca_cert:/tmp/credhub_cacert"]
    links: ["credhub"]
    depends_on: ["concourse-db","credhub"]
    ports: ["8082:8080"]
    environment:
      #CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8082
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CREDHUB_URL: https://credhub:9000
      CONCOURSE_CREDHUB_CLIENT_ID: credhub_client
      CONCOURSE_CREDHUB_CLIENT_SECRET: secret
     # CONCOURSE_CREDHUB_CA_CERT: /tmp/credhub_cacert/server_ca_cert.pem
      CONCOURSE_CREDHUB_INSECURE_SKIP_VERIFY: "true"

