#https://github.com/pivotal-cf/email-resource
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
      tag: latest 

resources:
  - name: send-an-email
    type: email
    source:
      smtp:
        host: ((smtp-host))
        port: ((smtp-port))
        username: ((smtp-username))
        password: ((smtp-password))
      from: ((email-from))
      to: [ ((email-to)) ]

send-an-email-success: &send-an-email-success
    params:
      subject_text: "[SUCCESS] ${pipeline_name}/${BUILD_JOB_NAME}/${BUILD_NAME} "
      body: email-out/generated-body
send-an-email-failure: &send-an-email-failure
    params:
      subject_text: "[FAILURE] ${pipeline_name}/${BUILD_JOB_NAME}/${BUILD_NAME} "
      body: email-out/generated-body

jobs:

  - name: send-email-direct
    plan:
      - put: send-an-email
        params:
          subject_text: "email-out/generated-subject"
          body_text: "email-out/generated-body"

  - name: send-email
    plan:
      - task: prep-email
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/buildroot
              tag: git
          params:
            OUTPUT_SUBJECT_FILE_NAME: generated-subject
            OUTPUT_BODY_FILE_NAME: generated-body
          run:
            path: sh
            args:
            - -exc
            - |
              # ensure you esape the ${BUILD_ID} variable with leading \
              echo -e "Email resource demo on $(date): build \${BUILD_ID}" > email-out/${OUTPUT_SUBJECT_FILE_NAME}
              echo -e "Cheers!\n\n \
              Build ID: \${BUILD_ID} \n \
              Build Name: \${BUILD_NAME} \n \
              Build Job Name: \${BUILD_JOB_NAME} \n \
              Build Pipeline Name: \${pipeline_name} \n \
              ATC External URL: \${ATC_EXTERNAL_URL}" > email-out/${OUTPUT_BODY_FILE_NAME}
          outputs:
          - name: email-out
        on_success:
          put: send-an-email
          <<: *send-an-email-success
        on_failure:
          put: send-an-email
          <<: *send-an-email-failure

      - put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body

