foundation: awstest

s3:
  endpoint: https://s3.ap-northeast-2.amazonaws.com
  access_key_id: ((s3_access_key_id))
  secret_access_key: ((s3_secret_access_key))
  region_name: "ap-northeast-2"
  buckets:
    platform_files: mkim-platform-automation
    platform_backup: mkim-bbr-backup


git:
  platform_automation_pipelines:
    uri: git@github.com:myminseok/platform-automation-template.git
    branch: master
  platform_automation_configs:
    uri: git@github.com:myminseok/platform-automation-template.git
    branch: master
  user: 
    email: ((git_user_email))
    username: "Platform Automation Bot"
  private_key: ((git_private_key.private_key))

credhub:
  server: https://192.168.67.1:9000
  #server: https://credhub:9000 ## docker-compose env
  #ca_cert: ((credhub_ca_cert.certificate))
  ca_cert: ""
  client: ((credhub_client.username))
  secret: ((credhub_client.password))

pivnet: 
  token: ((pivnet_token))

certificate:
   generate:
      dns_privider_access_key: ((s3_access_key_id))
      dns_privider_access_secret_key: ((s3_secret_access_key))
      dns_provider_region: "ap-northeast-2"
      subdomain: awstest.pcfdemo.net
      dns_provider_hosted_zone_id:   # create on aws inadvance.
      letsencrypt_email:
   credhub_key_name: networking_poe_ssl_certs_0 # map to tas.yml.
